# Generated by Django 6.1.2 on 2026-10-08 10:04

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('ent', 'ENT (Otorhinolaryngology)'), ('gastroenterology', 'Gastroenterology'), ('gynecology', 'Gynecology & Obstetrics'), ('nephrology', 'Nephrology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('ophthalmology', 'Ophthalmology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('urology', 'Urology'), ('other', 'Other')], max_length=32)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +91 98765 43210.', regex='^\\+?[0-9][0-9\\s\\-()]{6,18}[0-9]$')])),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(70)])),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['specialization'], name='doctor_specialization_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='doctor_email_ci_unique'), models.CheckConstraint(condition=models.Q(('years_of_experience__lte', 70)), name='doctor_experience_lte_70')],
            },
        ),
    ]
